### ISSUE TITLE
firmware upload fails

### ISSUE THREAD

**Issue by llorban** [strawlab/triggerbox#4]
Here is the error

```
mkdir -p build-uno
make reset
make[1]: Entering directory '/home/flightlab/Documents/triggerbox-master/firmware/triggerbox'
make[1]: *** No rule to make target 'reset'.  Stop.
make[1]: Leaving directory '/home/flightlab/Documents/triggerbox-master/firmware/triggerbox'
/usr/share/arduino/Arduino.mk:1408: recipe for target 'upload' failed
make: *** [upload] Error 2
```

The Arduino IDE is running and I am able to get "board info" so connection to the Arduino is confirmed. The Arduino is on port /dev/ttyACM0 and the make file appears to look there (/dev/ttyACM*)

**Comment by astraw** [comment]
Why are you trying to do `make reset`? As specified in `README.md`, try one of these:

    make -f Makefile.nano upload # <- Do this for Arduino Nano
    make -f Makefile.uno upload # <- Do this for Arduino Uno

**Comment by llorban** [comment]
I didn't do a `make reset` -- followed the readme.md word for word

**Comment by llorban** [comment]
Here is the full output including my command

```
make -f Makefile.uno upload
-------------------------
Arduino.mk Configuration:
- [AUTODETECTED]       CURRENT_OS = LINUX 
- [USER]               ARDUINO_DIR = /usr/share/arduino 
- [COMPUTED]           ARDMK_DIR = /usr/share/arduino (relative to Common.mk)
- [AUTODETECTED]       ARDUINO_VERSION = 105 
- [DEFAULT]            ARCHITECTURE =  
- [DEFAULT]            VENDOR = arduino 
- [DEFAULT]            ARDUINO_SKETCHBOOK =  
- [BUNDLED]            AVR_TOOLS_DIR = /usr/share/arduino/hardware/tools/avr (in Arduino distribution)
- [COMPUTED]           ARDUINO_LIB_PATH = /usr/share/arduino/libraries (from ARDUINO_DIR)
- [COMPUTED]           ARDUINO_VAR_PATH = /usr/share/arduino/hardware/arduino//variants (from ARDUINO_DIR)
- [COMPUTED]           BOARDS_TXT = /usr/share/arduino/hardware/arduino//boards.txt (from ARDUINO_DIR)
- [DEFAULT]            USER_LIB_PATH = /libraries (in user sketchbook)
- [DEFAULT]            PRE_BUILD_HOOK = pre-build-hook.sh 
- [USER]               BOARD_TAG = uno 
- [COMPUTED]           CORE = arduino (from build.core)
- [COMPUTED]           VARIANT = standard (from build.variant)
- [COMPUTED]           OBJDIR = build-uno (from BOARD_TAG)
- [COMPUTED]           ARDUINO_CORE_PATH = /usr/share/arduino/hardware/arduino//cores/arduino (from ARDUINO_DIR, BOARD_TAG and boards.txt)
- [DETECTED]           MONITOR_BAUDRATE = 115200  (in sketch)
- [DEFAULT]            OPTIMIZATION_LEVEL = s 
- [DEFAULT]            MCU_FLAG_NAME = mmcu 
- [DEFAULT]            CFLAGS_STD =  
- [DEFAULT]            CXXFLAGS_STD =  
- [COMPUTED]           DEVICE_PATH = /dev/trig* /dev/ttyACM* (from MONITOR_PORT)
- [DEFAULT]            FORCE_MONITOR_PORT =  
- [AUTODETECTED]       Size utility: AVR-aware for enhanced output
-
-                      ARDUINO_LIBS =
- [SYSTEM]               EEPROM
- [SYSTEM]               SPI
- [SYSTEM]               UDEV
- [COMPUTED]           BOOTLOADER_PARENT = /usr/share/arduino/hardware/arduino//bootloaders (from ARDUINO_DIR)
- [COMPUTED]           ARDMK_VERSION = 1.5 
- [COMPUTED]           CC_VERSION = 4.9.2 (avr-gcc)
-------------------------
mkdir -p build-uno
make reset
make[1]: Entering directory '/home/flightlab/Documents/triggerbox-master/firmware/triggerbox'
make[1]: *** No rule to make target 'reset'.  Stop.
make[1]: Leaving directory '/home/flightlab/Documents/triggerbox-master/firmware/triggerbox'
/usr/share/arduino/Arduino.mk:1408: recipe for target 'upload' failed
make: *** [upload] Error 2
```

**Comment by astraw** [comment]
Are you running `make -f Makefile.uno upload` in the directory `firmware/triggerbox`? I guess so.

This is very strange. The file `Makefile.uno` is just sets a few configuration variables and then defers to the file `/usr/share/arduino/Arduino.mk`, which is obviously found. This `Arduino.mk` then calls another make target (`make reset`) which is in the `Arduino.mk` file again.

Perhaps try renaming `Makefile.uno` to `Makefile` and then, instead of `make -f Makefile.uno upload`, just run `make upload`.

**Comment by llorban** [comment]
Thank you, your suggestion helped get past this error, but it failed with another one: 

```
make upload
-------------------------
Arduino.mk Configuration:
- [AUTODETECTED]       CURRENT_OS = LINUX 
- [USER]               ARDUINO_DIR = /usr/share/arduino 
- [COMPUTED]           ARDMK_DIR = /usr/share/arduino (relative to Common.mk)
- [AUTODETECTED]       ARDUINO_VERSION = 105 
- [DEFAULT]            ARCHITECTURE =  
- [DEFAULT]            VENDOR = arduino 
- [DEFAULT]            ARDUINO_SKETCHBOOK =  
- [BUNDLED]            AVR_TOOLS_DIR = /usr/share/arduino/hardware/tools/avr (in Arduino distribution)
- [COMPUTED]           ARDUINO_LIB_PATH = /usr/share/arduino/libraries (from ARDUINO_DIR)
- [COMPUTED]           ARDUINO_VAR_PATH = /usr/share/arduino/hardware/arduino//variants (from ARDUINO_DIR)
- [COMPUTED]           BOARDS_TXT = /usr/share/arduino/hardware/arduino//boards.txt (from ARDUINO_DIR)
- [DEFAULT]            USER_LIB_PATH = /libraries (in user sketchbook)
- [DEFAULT]            PRE_BUILD_HOOK = pre-build-hook.sh 
- [USER]               BOARD_TAG = uno 
- [COMPUTED]           CORE = arduino (from build.core)
- [COMPUTED]           VARIANT = standard (from build.variant)
- [COMPUTED]           OBJDIR = build-uno (from BOARD_TAG)
- [COMPUTED]           ARDUINO_CORE_PATH = /usr/share/arduino/hardware/arduino//cores/arduino (from ARDUINO_DIR, BOARD_TAG and boards.txt)
- [DETECTED]           MONITOR_BAUDRATE = 115200  (in sketch)
- [DEFAULT]            OPTIMIZATION_LEVEL = s 
- [DEFAULT]            MCU_FLAG_NAME = mmcu 
- [DEFAULT]            CFLAGS_STD =  
- [DEFAULT]            CXXFLAGS_STD =  
- [COMPUTED]           DEVICE_PATH = /dev/trig* /dev/ttyACM* (from MONITOR_PORT)
- [DEFAULT]            FORCE_MONITOR_PORT =  
- [AUTODETECTED]       Size utility: AVR-aware for enhanced output
-
-                      ARDUINO_LIBS =
- [SYSTEM]               EEPROM
- [SYSTEM]               SPI
- [SYSTEM]               UDEV
- [COMPUTED]           BOOTLOADER_PARENT = /usr/share/arduino/hardware/arduino//bootloaders (from ARDUINO_DIR)
- [COMPUTED]           ARDMK_VERSION = 1.5 
- [COMPUTED]           CC_VERSION = 4.9.2 (avr-gcc)
-------------------------
mkdir -p build-uno
/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -x c++ -include Arduino.h -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105  -D__PROG_TYPES_COMPAT__ -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/standard    -I/usr/share/arduino/libraries/EEPROM    -I/usr/share/arduino/libraries/SPI    -I/usr/share/arduino/libraries/UDEV   -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  triggerbox.ino -o build-uno/triggerbox.o
/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105  -D__PROG_TYPES_COMPAT__ -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/standard    -I/usr/share/arduino/libraries/EEPROM    -I/usr/share/arduino/libraries/SPI    -I/usr/share/arduino/libraries/UDEV   -Wall -ffunction-sections -fdata-sections -Os  /usr/share/arduino/hardware/arduino//cores/arduino/wiring.c -o build-uno/core/wiring.o
/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105  -D__PROG_TYPES_COMPAT__ -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/standard    -I/usr/share/arduino/libraries/EEPROM    -I/usr/share/arduino/libraries/SPI    -I/usr/share/arduino/libraries/UDEV   -Wall -ffunction-sections -fdata-sections -Os  /usr/share/arduino/hardware/arduino//cores/arduino/WInterrupts.c -o build-uno/core/WInterrupts.o
/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105  -D__PROG_TYPES_COMPAT__ -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/standard    -I/usr/share/arduino/libraries/EEPROM    -I/usr/share/arduino/libraries/SPI    -I/usr/share/arduino/libraries/UDEV   -Wall -ffunction-sections -fdata-sections -Os  /usr/share/arduino/hardware/arduino//cores/arduino/wiring_digital.c -o build-uno/core/wiring_digital.o
/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105  -D__PROG_TYPES_COMPAT__ -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/standard    -I/usr/share/arduino/libraries/EEPROM    -I/usr/share/arduino/libraries/SPI    -I/usr/share/arduino/libraries/UDEV   -Wall -ffunction-sections -fdata-sections -Os  /usr/share/arduino/hardware/arduino//cores/arduino/wiring_pulse.c -o build-uno/core/wiring_pulse.o
/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105  -D__PROG_TYPES_COMPAT__ -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/standard    -I/usr/share/arduino/libraries/EEPROM    -I/usr/share/arduino/libraries/SPI    -I/usr/share/arduino/libraries/UDEV   -Wall -ffunction-sections -fdata-sections -Os  /usr/share/arduino/hardware/arduino//cores/arduino/wiring_analog.c -o build-uno/core/wiring_analog.o
/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105  -D__PROG_TYPES_COMPAT__ -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/standard    -I/usr/share/arduino/libraries/EEPROM    -I/usr/share/arduino/libraries/SPI    -I/usr/share/arduino/libraries/UDEV   -Wall -ffunction-sections -fdata-sections -Os  /usr/share/arduino/hardware/arduino//cores/arduino/wiring_shift.c -o build-uno/core/wiring_shift.o
/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105  -D__PROG_TYPES_COMPAT__ -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/standard    -I/usr/share/arduino/libraries/EEPROM    -I/usr/share/arduino/libraries/SPI    -I/usr/share/arduino/libraries/UDEV   -Wall -ffunction-sections -fdata-sections -Os  /usr/share/arduino/hardware/arduino//cores/arduino/avr-libc/realloc.c -o build-uno/core/avr-libc/realloc.o
/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105  -D__PROG_TYPES_COMPAT__ -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/standard    -I/usr/share/arduino/libraries/EEPROM    -I/usr/share/arduino/libraries/SPI    -I/usr/share/arduino/libraries/UDEV   -Wall -ffunction-sections -fdata-sections -Os  /usr/share/arduino/hardware/arduino//cores/arduino/avr-libc/malloc.c -o build-uno/core/avr-libc/malloc.o
/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105  -D__PROG_TYPES_COMPAT__ -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/standard    -I/usr/share/arduino/libraries/EEPROM    -I/usr/share/arduino/libraries/SPI    -I/usr/share/arduino/libraries/UDEV   -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  /usr/share/arduino/hardware/arduino//cores/arduino/IPAddress.cpp -o build-uno/core/IPAddress.o
/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105  -D__PROG_TYPES_COMPAT__ -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/standard    -I/usr/share/arduino/libraries/EEPROM    -I/usr/share/arduino/libraries/SPI    -I/usr/share/arduino/libraries/UDEV   -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  /usr/share/arduino/hardware/arduino//cores/arduino/Tone.cpp -o build-uno/core/Tone.o
/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105  -D__PROG_TYPES_COMPAT__ -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/standard    -I/usr/share/arduino/libraries/EEPROM    -I/usr/share/arduino/libraries/SPI    -I/usr/share/arduino/libraries/UDEV   -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  /usr/share/arduino/hardware/arduino//cores/arduino/WString.cpp -o build-uno/core/WString.o
/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105  -D__PROG_TYPES_COMPAT__ -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/standard    -I/usr/share/arduino/libraries/EEPROM    -I/usr/share/arduino/libraries/SPI    -I/usr/share/arduino/libraries/UDEV   -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  /usr/share/arduino/hardware/arduino//cores/arduino/WMath.cpp -o build-uno/core/WMath.o
/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105  -D__PROG_TYPES_COMPAT__ -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/standard    -I/usr/share/arduino/libraries/EEPROM    -I/usr/share/arduino/libraries/SPI    -I/usr/share/arduino/libraries/UDEV   -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  /usr/share/arduino/hardware/arduino//cores/arduino/Print.cpp -o build-uno/core/Print.o
/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105  -D__PROG_TYPES_COMPAT__ -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/standard    -I/usr/share/arduino/libraries/EEPROM    -I/usr/share/arduino/libraries/SPI    -I/usr/share/arduino/libraries/UDEV   -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  /usr/share/arduino/hardware/arduino//cores/arduino/HID.cpp -o build-uno/core/HID.o
/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105  -D__PROG_TYPES_COMPAT__ -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/standard    -I/usr/share/arduino/libraries/EEPROM    -I/usr/share/arduino/libraries/SPI    -I/usr/share/arduino/libraries/UDEV   -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  /usr/share/arduino/hardware/arduino//cores/arduino/Stream.cpp -o build-uno/core/Stream.o
/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105  -D__PROG_TYPES_COMPAT__ -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/standard    -I/usr/share/arduino/libraries/EEPROM    -I/usr/share/arduino/libraries/SPI    -I/usr/share/arduino/libraries/UDEV   -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  /usr/share/arduino/hardware/arduino//cores/arduino/USBCore.cpp -o build-uno/core/USBCore.o
/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105  -D__PROG_TYPES_COMPAT__ -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/standard    -I/usr/share/arduino/libraries/EEPROM    -I/usr/share/arduino/libraries/SPI    -I/usr/share/arduino/libraries/UDEV   -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  /usr/share/arduino/hardware/arduino//cores/arduino/new.cpp -o build-uno/core/new.o
/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105  -D__PROG_TYPES_COMPAT__ -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/standard    -I/usr/share/arduino/libraries/EEPROM    -I/usr/share/arduino/libraries/SPI    -I/usr/share/arduino/libraries/UDEV   -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  /usr/share/arduino/hardware/arduino//cores/arduino/main.cpp -o build-uno/core/main.o
/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105  -D__PROG_TYPES_COMPAT__ -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/standard    -I/usr/share/arduino/libraries/EEPROM    -I/usr/share/arduino/libraries/SPI    -I/usr/share/arduino/libraries/UDEV   -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  /usr/share/arduino/hardware/arduino//cores/arduino/HardwareSerial.cpp -o build-uno/core/HardwareSerial.o
/usr/share/arduino/hardware/arduino//cores/arduino/HardwareSerial.cpp: In function ‘void store_char(unsigned char, ring_buffer*)’:
/usr/share/arduino/hardware/arduino//cores/arduino/HardwareSerial.cpp:100:9: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (i != buffer->tail) {
         ^
/usr/share/arduino/hardware/arduino//cores/arduino/HardwareSerial.cpp: In function ‘void __vector_18()’:
/usr/share/arduino/hardware/arduino//cores/arduino/HardwareSerial.cpp:129:21: warning: unused variable ‘c’ [-Wunused-variable]
       unsigned char c = UDR0;
                     ^
/usr/share/arduino/hardware/arduino//cores/arduino/HardwareSerial.cpp: In member function ‘void HardwareSerial::begin(long unsigned int, byte)’:
/usr/share/arduino/hardware/arduino//cores/arduino/HardwareSerial.cpp:370:11: warning: unused variable ‘current_config’ [-Wunused-variable]
   uint8_t current_config;
           ^
/usr/share/arduino/hardware/arduino//cores/arduino/HardwareSerial.cpp: In member function ‘virtual size_t HardwareSerial::write(uint8_t)’:
/usr/share/arduino/hardware/arduino//cores/arduino/HardwareSerial.cpp:469:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   while (i == _tx_buffer->tail)
            ^
/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105  -D__PROG_TYPES_COMPAT__ -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/standard    -I/usr/share/arduino/libraries/EEPROM    -I/usr/share/arduino/libraries/SPI    -I/usr/share/arduino/libraries/UDEV   -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  /usr/share/arduino/hardware/arduino//cores/arduino/CDC.cpp -o build-uno/core/CDC.o
/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105  -D__PROG_TYPES_COMPAT__ -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/standard    -I/usr/share/arduino/libraries/EEPROM    -I/usr/share/arduino/libraries/SPI    -I/usr/share/arduino/libraries/UDEV   -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  /usr/share/arduino/libraries/EEPROM/EEPROM.cpp -o build-uno/libs/EEPROM/EEPROM.o
/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105  -D__PROG_TYPES_COMPAT__ -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/standard    -I/usr/share/arduino/libraries/EEPROM    -I/usr/share/arduino/libraries/SPI    -I/usr/share/arduino/libraries/UDEV   -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  /usr/share/arduino/libraries/SPI/SPI.cpp -o build-uno/libs/SPI/SPI.o
/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105  -D__PROG_TYPES_COMPAT__ -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/standard    -I/usr/share/arduino/libraries/EEPROM    -I/usr/share/arduino/libraries/SPI    -I/usr/share/arduino/libraries/UDEV   -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  /usr/share/arduino/libraries/UDEV/UDEV.cpp -o build-uno/libs/UDEV/UDEV.o
/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs build-uno/libcore.a  build-uno/core/WInterrupts.o  build-uno/core/wiring.o  build-uno/core/wiring_pulse.o  build-uno/core/wiring_analog.o  build-uno/core/wiring_digital.o  build-uno/core/wiring_shift.o  build-uno/core/avr-libc/realloc.o  build-uno/core/avr-libc/malloc.o  build-uno/core/Tone.o  build-uno/core/Print.o  build-uno/core/Stream.o  build-uno/core/WString.o  build-uno/core/new.o  build-uno/core/main.o  build-uno/core/IPAddress.o  build-uno/core/USBCore.o  build-uno/core/HID.o  build-uno/core/WMath.o  build-uno/core/CDC.o  build-uno/core/HardwareSerial.o  build-uno/libs/EEPROM/EEPROM.o build-uno/libs/SPI/SPI.o build-uno/libs/UDEV/UDEV.o     
/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -Wl,--gc-sections -Os -o build-uno/triggerbox.elf build-uno/triggerbox.o build-uno/libcore.a  -lc -lm
/usr/share/arduino/hardware/tools/avr/bin/avr-objcopy -O ihex -R .eeprom build-uno/triggerbox.elf build-uno/triggerbox.hex

/usr/share/arduino/hardware/tools/avr/bin/avr-size --mcu=atmega328p -C --format=avr build-uno/triggerbox.elf
AVR Memory Usage
----------------
Device: atmega328p

Program:    6372 bytes (19.4% Full)
(.text + .data + .bootloader)

Data:        243 bytes (11.9% Full)
(.data + .bss + .noinit)


make reset
make[1]: Entering directory '/home/flightlab/Documents/triggerbox-master/firmware/triggerbox'
/usr/bin/ard-reset-arduino  /dev/ttyACM0
Traceback (most recent call last):
  File "/usr/bin/ard-reset-arduino", line 34, in <module>
    ser = serial.Serial(args.port[0], 115200)
  File "/usr/lib/python2.7/dist-packages/serial/serialutil.py", line 180, in __init__
    self.open()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 294, in open
    raise SerialException(msg.errno, "could not open port %s: %s" % (self._port, msg))
serial.serialutil.SerialException: [Errno 13] could not open port /dev/ttyACM0: [Errno 13] Permission denied: '/dev/ttyACM0'
/usr/share/arduino/Arduino.mk:1432: recipe for target 'reset' failed
make[1]: *** [reset] Error 1
make[1]: Leaving directory '/home/flightlab/Documents/triggerbox-master/firmware/triggerbox'
/usr/share/arduino/Arduino.mk:1408: recipe for target 'upload' failed
make: *** [upload] Error 2

```

**Comment by astraw** [comment]
If you look at the error, you will see `Permission denied: '/dev/ttyACM0'`. There are a few ways to deal with this. Probably easiest is to run the command with superuser privileges: `sudo make upload`.

**Comment by llorban** [comment]
I think this worked-- here is the output: 

```
-------------------------
Arduino.mk Configuration:
- [AUTODETECTED]       CURRENT_OS = LINUX 
- [USER]               ARDUINO_DIR = /usr/share/arduino 
- [COMPUTED]           ARDMK_DIR = /usr/share/arduino (relative to Common.mk)
- [AUTODETECTED]       ARDUINO_VERSION = 105 
- [DEFAULT]            ARCHITECTURE =  
- [DEFAULT]            VENDOR = arduino 
- [DEFAULT]            ARDUINO_SKETCHBOOK =  
- [BUNDLED]            AVR_TOOLS_DIR = /usr/share/arduino/hardware/tools/avr (in Arduino distribution)
- [COMPUTED]           ARDUINO_LIB_PATH = /usr/share/arduino/libraries (from ARDUINO_DIR)
- [COMPUTED]           ARDUINO_VAR_PATH = /usr/share/arduino/hardware/arduino//variants (from ARDUINO_DIR)
- [COMPUTED]           BOARDS_TXT = /usr/share/arduino/hardware/arduino//boards.txt (from ARDUINO_DIR)
- [DEFAULT]            USER_LIB_PATH = /libraries (in user sketchbook)
- [DEFAULT]            PRE_BUILD_HOOK = pre-build-hook.sh 
- [USER]               BOARD_TAG = uno 
- [COMPUTED]           CORE = arduino (from build.core)
- [COMPUTED]           VARIANT = standard (from build.variant)
- [COMPUTED]           OBJDIR = build-uno (from BOARD_TAG)
- [COMPUTED]           ARDUINO_CORE_PATH = /usr/share/arduino/hardware/arduino//cores/arduino (from ARDUINO_DIR, BOARD_TAG and boards.txt)
- [DETECTED]           MONITOR_BAUDRATE = 115200  (in sketch)
- [DEFAULT]            OPTIMIZATION_LEVEL = s 
- [DEFAULT]            MCU_FLAG_NAME = mmcu 
- [DEFAULT]            CFLAGS_STD =  
- [DEFAULT]            CXXFLAGS_STD =  
- [COMPUTED]           DEVICE_PATH = /dev/trig* /dev/ttyACM* (from MONITOR_PORT)
- [DEFAULT]            FORCE_MONITOR_PORT =  
- [AUTODETECTED]       Size utility: AVR-aware for enhanced output
-
-                      ARDUINO_LIBS =
- [SYSTEM]               EEPROM
- [SYSTEM]               SPI
- [SYSTEM]               UDEV
- [COMPUTED]           BOOTLOADER_PARENT = /usr/share/arduino/hardware/arduino//bootloaders (from ARDUINO_DIR)
- [COMPUTED]           ARDMK_VERSION = 1.5 
- [COMPUTED]           CC_VERSION = 4.9.2 (avr-gcc)
-------------------------
mkdir -p build-uno
/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -x c++ -include Arduino.h -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105  -D__PROG_TYPES_COMPAT__ -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/standard    -I/usr/share/arduino/libraries/EEPROM    -I/usr/share/arduino/libraries/SPI    -I/usr/share/arduino/libraries/UDEV   -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  triggerbox.ino -o build-uno/triggerbox.o
/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -Wl,--gc-sections -Os -o build-uno/triggerbox.elf build-uno/triggerbox.o build-uno/libcore.a  -lc -lm
/usr/share/arduino/hardware/tools/avr/bin/avr-objcopy -O ihex -R .eeprom build-uno/triggerbox.elf build-uno/triggerbox.hex

/usr/share/arduino/hardware/tools/avr/bin/avr-size --mcu=atmega328p -C --format=avr build-uno/triggerbox.elf
AVR Memory Usage
----------------
Device: atmega328p

Program:    6372 bytes (19.4% Full)
(.text + .data + .bootloader)

Data:        243 bytes (11.9% Full)
(.data + .bss + .noinit)


make reset
make[1]: Entering directory '/home/llorban/Documents/triggerbox-master/firmware/triggerbox'
/usr/bin/ard-reset-arduino  /dev/ttyACM0
make[1]: Leaving directory '/home/llorban/Documents/triggerbox-master/firmware/triggerbox'
make do_upload
make[1]: Entering directory '/home/llorban/Documents/triggerbox-master/firmware/triggerbox'
/usr/share/arduino/hardware/tools/avr/../avrdude -q -V -p atmega328p -C /usr/share/arduino/hardware/tools/avr/../avrdude.conf -D -c arduino -b 115200 -P /dev/ttyACM0 \
		-U flash:w:build-uno/triggerbox.hex:i

avrdude: AVR device initialized and ready to accept instructions
avrdude: Device signature = 0x1e950f (probably m328p)
avrdude: reading input file "build-uno/triggerbox.hex"
avrdude: writing flash (6372 bytes):
avrdude: 6372 bytes of flash written

avrdude: safemode: Fuses OK (E:00, H:00, L:00)

avrdude done.  Thank you.

make[1]: Leaving directory '/home/llorban/Documents/triggerbox-master/firmware/triggerbox'

```
